const products = {
    necklace: [
        { name: 'Horsebit Necklace', price: '557,000원', badge: 'best', img: 'img/상세페이지.jpg' , link: '상세페이지.html'},
        { name: 'Éclat Chain Necklace', price: '57,000원', badge: 'best', img: 'img/best2.jpg' },
        { name: 'Muse Pearl Necklace', price: '84,000원', badge: 'new', img: 'img/Pearl Line.jpg' },
        { name: 'Lumière Pendant', price: '57,600원', originalPrice: '72,000원', badge: 'sale', img: 'img/neck.jpg' },
        { name: 'Soleil Layered Necklace',  price: '96,000원', img: 'img/lookbook1.png' },
        { name: 'Céleste Star Necklace',  price: '248,000원', img: 'img/neck1.jpg' },
        { name: 'Douceur Choker',  price: '48,000원', badge: 'new', img: 'img/neck2.jpg' },
        { name: 'Minuit Long Necklace',  price: '112,000원', img: 'img/neck3.jpg' },
        { name: 'Aurore Initial Necklace', price: '135,000원', img: 'img/neck4.jpg' },
        { name: 'Perle Drop Necklace', price: '178,000원', badge: 'best', img: 'img/best4.jpg' },
    ],
    earring: [
        { name: 'Céleste Drop Earring', price: '29,000원', badge: 'best', img: 'img/best3.jpg' },
        { name: 'Éternel Circle Earring', price: '68,000원', badge: 'new', img: 'img/Circle Éternel.jpg' },
        { name: 'Lumière Earring', price: '32,000원',  img: 'img/Lumière.jpg' },
        { name: 'Lumière Earring', price: '32,000원',  img: 'img/lookbook4.png' },
    ],
    ring: [
        { name: 'Harmonie Trio Ring',  price: '77,000원', badge: 'best', img: 'img/best1.jpg' },
        { name: 'Soleil Birthstone Ring', price: '124,000원', img: 'img/ring1.jpg' },
        { name: 'Mémoire Signet Ring',  price: '98,000원', badge: 'new', img: 'img/Harmonie Trio.jpg' },
        { name: 'Mémoire Signet Ring',  price: '98,000원', badge: 'new', img: 'img/lookbook3.png' },
    ],
    bracelet: [
        { name: 'Lien Chain Bracelet',  price: '48,000원', badge: 'best', img: 'img/lookbook2.png' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla.jpg' },
        { name: 'Lien Chain Bracelet',  price: '48,000원', badge: 'new', img: 'img/bla1.jpg' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla2.jpg' },
        { name: 'Lien Chain Bracelet',  price: '48,000원', badge: 'best', img: 'img/bla3.jpg' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla4.jpg' },
        { name: 'Lien Chain Bracelet',  price: '48,000원', img: 'img/bla5.jpg' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla6.jpg' },
        { name: 'Lien Chain Bracelet',  price: '48,000원', img: 'img/bla7.jpg' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla8.jpg' },
        { name: 'Lien Chain Bracelet',  price: '48,000원',img: 'img/bla9.jpg' },
        { name: 'Douceur Bangle',  price: '86,000원', img: 'img/bla10.jpg' },
    ],
    watch: [
        { name: 'Minuit Watch', price: '380,000원', badge: 'new', img: 'img/watch.jpg' },
        { name: 'Lumière Watch',  price: '245,000원', img: 'img/watch1.jpg' },
        { name: 'Minuit Watch', price: '380,000원', badge: 'best', img: 'img/watch2.jpg' },
        { name: 'Lumière Watch',  price: '245,000원', img: 'img/watch3.jpg' },
    ],
    couple: [
        { name: 'Lumière Couple Ring',  price: '154,000원', badge: 'best', img: 'img/couplering.jpg' },
        { name: 'Éclat Couple Bracelet', price: '96,000원', badge: 'new', img: 'img/couplering6.jpg' },
        { name: 'Éclat Couple Bracelet', price: '96,000원', badge: 'new', img: 'img/couplering1.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering2.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering7.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering3.jpg' },
        { name: 'Lumière Couple Ring',  price: '154,000원', img: 'img/couplering4.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering5.jpg' },
        { name: 'Lumière Couple Ring',  price: '154,000원', img: 'img/couplering8.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering9.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering10.jpg' },
        { name: 'Lumière Couple Ring',  price: '154,000원', img: 'img/couplering11.jpg' },
        { name: 'Céleste Couple Necklace',  price: '128,000원', img: 'img/couplering12.jpg' },
    ],
};